---
abstract: "C#'s string Hashing Algorithm in V3.5 "
author:
  - 'Chen Gang <yikuyiku.com@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-StringHash-FromCSharp35-XS
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.01
